FROM ubuntu:16.04
RUN apt-get update && apt-get install -y openssh-server
RUN mkdir /var/run/sshd
RUN echo 'root:screencast' | chpasswd  && \
    useradd jenkins -U -s /bin/bash && \
    echo 'jenkins:Error404' | chpasswd 
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN apt-get install openjdk-8-jdk -y && \
    apt-get install unzip -y && \
    apt-get install apache2 -y && \
    apt-get install sudo -y && \
    apt-get install nmap -y
COPY ["sonar-scanner-cli-3.2.0.1227-linux.zip","apache-maven-3.5.4-bin.zip","/opt/"]
RUN  unzip /opt/apache-maven-3.5.4-bin.zip -d /opt \
     && unzip /opt/sonar-scanner-cli-3.2.0.1227-linux.zip -d /opt \
     && rm /opt/sonar-scanner-cli-3.2.0.1227-linux.zip \
     && rm /opt/apache-maven-3.5.4-bin.zip
ENV PATH="/opt/apache-maven-3.5.4/bin:/opt/sonar-scanner-3.2.0.1227-linux/bin:$PATH"
ENV JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
RUN sudo adduser jenkins sudo && \
    su jenkins && \
    sudo mkdir /jenkins && \
    sudo mkdir /home/jenkins && \
    sudo chmod -R 777 /jenkins && \
    sudo chmod -R 777 /home/jenkins
# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd
ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]